---
- name: Jenkins and Docker Setup
  hosts: localhost
  remote_user: ec2-user
  become: true

  vars:
    maven_version: "3.9.5"
    maven_home: "/opt/apache-maven-{{ maven_version }}"
    jenkins_repo_url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    jenkins_gpg_key: "https://pkg.jenkins.io/redhat/jenkins.io-2023.key"

  tasks:
    - name: Install dependencies
      yum:
        name:
          - wget
          - git
          - yum-utils
        state: present

    - name: Install Java 17
      yum:
        name: java-17-amazon-corretto-headless
        state: present

    - name: Add Jenkins repository
      get_url:
        url: "{{ jenkins_repo_url }}"
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: "{{ jenkins_gpg_key }}"

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Wait for Jenkins to be ready
      wait_for:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        timeout: 30

    - name: Get initial Jenkins admin password
      ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: jenkins_password

    - name: Display initial Jenkins admin password
      debug:
        var: jenkins_password.stdout

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Set proper permissions on Docker socket
      file:
        path: "/var/run/docker.sock"
        state: file
        mode: "660"
        owner: root
        group: docker

    - block:
        - name: Download and extract Maven
          unarchive:
            src: "https://downloads.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
            dest: /opt
            remote_src: yes

        - name: Create Maven symlink in /usr/bin
          file:
            src: "{{ maven_home }}/bin/mvn"
            dest: /usr/bin/mvn
            state: link

        - name: Configure Maven environment variables
          lineinfile:
            dest: "/etc/profile.d/maven.sh"
            line: "{{ item }}"
            create: yes
            state: present
          loop:
            - "export M2_HOME={{ maven_home }}"
            - "export PATH=$PATH:$M2_HOME/bin"

        - name: Source Maven environment file
          shell: "source /etc/profile.d/maven.sh"
          args:
            executable: /bin/bash
